---
arista-switch-1:
  hostname: 192.168.1.10
  groups:
    - arista_switches
  data:
    platform: eos

arista-switch-2:
  hostname: 192.168.1.11
  groups:
    - arista_switches
  data:
    platform: eos
